config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :musicals

end

app/models/musical.rb
class Musical < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musicals_controller.rb
class MusicalsController < ApplicationController

  def index
    @musicals = Musical.all
  end

  def new
    @musical = Musical.new
  end

  def create
    @musical = Musical.create(musical_strong_params)
    if @musical.save
      redirect_to musicals_path
    else
      render root_path
    end
  end

  def show
    @musical = Musical.find(params[:id])
  end

  def edit
    @musical = Musical.find(params[:id])
  end

  def update
    @musical = Musical.find(params[:id])
    @musical.update_attributes!(musical_strong_params)

    redirect_to musicals_path
  end

  def destroy
    @musical = Musical.find(params[:id]).delete

    redirect_to musicals_path
  end

  private
  def musical_strong_params
    params.require(:musical).permit(:name, :actor)

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCrudMusicals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/musicals/edit.html.erb
<%= form_for @musical do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :actor %>
    <%= f.text_field :actor %>
  </p>
  <p>
    <%= f.submit 'Update Musical' %>
  </p>
<% end %>

app/views/musicals/index.html.erb
<p>
  <%= link_to 'Add Musical', new_musical_path %>
</p>

<div class="table">
  <table>
    <th>Name of Musical</th>
    <th>....</th>
    <th>Actor's Name</th>
    <% @musicals.each do |musical| %>
      <tr>
        <td><%= link_to "#{musical.name}", musical_path(musical) %></td>
        <td>....</td>
        <td><%= musical.actor %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/musicals/new.html.erb
<%= form_for @musical do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
  <p>
    <%= f.label :actor %>
    <%= f.text_field :actor %>
  </p>
  <p>
    <%= f.submit 'Create Musical' %>
  </p>
<% end %>

app/views/musicals/show.html.erb
<h3>Details on the Musical '<%= @musical.name %>'</h3>
<ul>
  <li>
    Name:  <%= @musical.name %><br>Actor:  <%= @musical.actor %>
  </li>
</ul>

<%= link_to 'Edit Musical', edit_musical_path %>
<%= link_to 'Delete Musical', musical_path, method: :delete %>

app/views/welcome/index.html.erb
<h2><%= link_to 'Musicals!', musicals_path %></h2>